=head1 NAME

Wanage and Warabe - APIs for server-side Web applications

=head1 DESCRIPTION

B<Wanage> and B<Warabe> are lightweight protocol-wrapper API layers
for building server-side Web applications.

  +------+   +------+   +------+      +------+      +------+
  |Your  |<->|Warabe|<->|Wanage|<---->|HTTP  |<---->|HTTP  |
  |  App.|   +------+   |      | CGI  |server| HTTP |client|
  |      |<------------>|      | PSGI |      |      |      |
  +------+              +------+      +------+      +------+
  
  App.       Common     Generic       TCP/HTTP
  specific   Web app.   HTTP          protocol
  logic      operations interpret.    handling

As shown in the figure, Warabe is an optional component build on top
of Wanage.

They are I<not> Web application frameworks (WAFs).  They only provide
abstraction for interpretation of HTTP requests and construction of
HTTP response in the level enough to create Web applications easily by
just understanding how HTTP works.  They does not define how you
organize your Web application.  They can be used in conjection with a
random Perl WAF, as long as it does not prevent you from accessing raw
HTTP request and/or response, if desired.

=head1 SEE ALSO

L<Wanage::HTTP>.

L<Warabe::App>.

=head1 DISTRIBUTION

Latest version of these modules are available in the Git repository:
<https://github.com/wakaba/wanage>.

There are no longer snapshot release version tarballs for Wanage and
Warabe.  You can just simply add the repository as a Git submodule of
your Git repository, if your application is using Git.

=head1 DEPENDENCIES

These modules require Perl 5.8 or later.  In addition, a few non-core
modules are required: L<Exporter::Lite>; L<Path::Class>; L<List::Ish>
(in C<modules/perl-ooutils> submodule); L<Web::URL> (in
C<modules/perl-web-url>; which depends on
C<modules/perl-web-encodings> and C<modules/perl-charclass>
submodules).

If you want to use optional modules (C<Warabe::App::Role::*>), more
module might be necessary.  See relevant documentations and source
codes of those modules.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012-2014 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
