=head1 NAME

Wanage::HTTP::Full - Wanage HTTP interface, full version

=head1 SYNOPSIS

  my $http = Wanage::HTTP::Full->new_cgi;
  my $http = Wanage::HTTP::Full->new_from_psgi_env ($env);

=head1 DESCRIPTION

The C<Wanage::HTTP::Full> class is a subclass of C<Wanage::HTTP> and
C<Wanage::HTTP::Role::*>.

=head1 AUTHOR

Wakaba <w@wuika.fam.cx>.

=head1 LICENSE

Copyright 2012 Wakaba <w@suika.fam.cx>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
